### ISSUE TITLE
Saved extent working some time, other times returns to same, unset location

### ISSUE THREAD

**Issue by slowe71** [roemhildtg/CMV_Widgets#13]
I am using your AppSettings widget and the save extents is working some of the time and then other times, upon opening it zooms to an extent that I did not set. When it does this, it is always the same spot that it returns to. Any idea what may be going on? Thanks!

**Comment by roemhildtg** [comment]
@slowe71, can you include information on what browser(s) you are having this problem with? And can you post your widget's config section?

Also please check and see if the latest version fixes the issue. I recently pushed some major changes and they may have an impact on the issue.

**Comment by slowe71** [comment]
Thanks for your help.  OK, more info:
I am typically using Chrome, but was also having issues in Firefox.  If I click on checkbox to set the layer visibility and extent and then just refresh without closing/re-opening, it works around half the time and then I am periodically getting the message shown below in the console and the set layer visibility does not work/extent does. If I click the checkboxes and then close/re-open the browser, that is when it zooms to the center of map, not the extent that I set, and I get the same error message in console.
 
![image](https://cloud.githubusercontent.com/assets/12254646/7860360/5d7dab5e-0516-11e5-9835-4e04222adc9b.png)

**Comment by roemhildtg** [comment]
I'm sure this probably isn't the issue but could you just double check you're using the latest version?

**Comment by slowe71** [comment]
Oops, sorry, meant to add that in the note above.  Yes, it appears that I am using the most recent.  The last note on the README file notes a change on 4/27/2015, which I believe is the most recent one.  In terms of configuration, all I did was add to viewer.js and move the AppSettings files to the widget folder.  I did not configure anything else of do anything with the php files, as that seemed optional.  I'm sure I messed something up, but I'm confused because it does work some of the time.  Another thing that may or may not be worth mentioning is that I am using an empty cache service for my levels of detail (as described here: https://github.com/cmv/cmv-docs/blob/master/configure/basemaps.md (Zooming in beyond Esri default scales or levels of detail).  This results in a bunch of errors in the console because the tiles do not exists (see below).  It does not seem that this would affect the AppSettings, but just wanted to mention it.            
![image](https://cloud.githubusercontent.com/assets/12254646/7882493/2fcb017c-05dc-11e5-9d16-fed5207f66e4.png)
Thanks again for all of your help!

**Comment by roemhildtg** [comment]
Go by the git commits for updates, I originally intended to update the readme for every update but I've been making a lot of changes lately to accommodate needs for the widget at work and haven't had time to update it. The most recent version was pushed 2 days ago.

**Comment by roemhildtg** [comment]
Could you try testing [this zip file](https://github.com/roemhildtg/CMV_Widgets/blob/master/cmv-app.zip) and comparing it to your code? I can't seem to reproduce the issue your having.

**Comment by slowe71** [comment]
Thanks again.  I downloaded the latest release yesterday and also just compared against your zip file, but I did not find anything that stood out.  While testing, though, I did notice that when the tool did not seem to be working (refresh of site did not open at the set extent), I was also getting this console error that I did not notice before: "Cannot read property 'decimalFormat' of undefined".  When this happens, the mapInfo widget does not display the scale or coordinates.  I found an issue that you submitted in past (https://github.com/cmv/cmv-app/issues/381). Seems like this could be related.  Did you ever resolve this issue with the mapInfo widget?
Thanks again for all of your help - Shana

**Comment by slowe71** [comment]
Thanks again.  I downloaded the latest release yesterday and also just compared against your zip file, but I did not find anything that stood out.  While testing, though, I did notice that when the tool did not seem to be working (refresh of site did not open at the set extent), I was also getting this console error that I did not notice before: "Cannot read property 'decimalFormat' of undefined".  When this happens, the mapInfo widget does not display the scale or coordinates.  I found an issue that you submitted in past (https://github.com/cmv/cmv-app/issues/381). Seems like this could be related.  Did you ever resolve this issue with the mapInfo widget?
Thanks again for all of your help - Shana

**Comment by roemhildtg** [comment]
The app settings will not load if other widgets fail first. This is because
app settings uses dojo ready to make sure all widgets are ready before
starting. When map info fails, so does app settings.

**Comment by roemhildtg** [comment]
Try disabling the map info widget and let me know if it works. I still haven't found a great solution to that other than getting rid of the dojo.number call inside.

**Comment by slowe71** [comment]
Looks like that did it.  For now I will just keep mapInfo disabled and maybe try to tweak it later.
Thank you for all or your help!!!!
