### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by jebu75** [roemhildtg/CMV_Widgets#2]
I am having problems getting this widget to work.  The issue is purely related to display, the retrieval of relationships and related records works great!  

I suspect that I'm having similar issues to those described here:
https://github.com/cmv/cmv-app/issues/233

What I can tell from my testing is that for one thing, the only tab position that works is 'left-h'.  If I use anything other, the tabcontainer and grid are not displayed.  Actually they are displayed but the contentPane the widget is placed in has a height of 0.

If I use the default 'left-h' tab position, then the tab is displayed but the grid is not.  It's in the dom but has it's container height is 0.  If I click on the pane splitter, do not need to drag, just the click is sufficient, then it causes the widget to redraw and everything looks fine.

Any ideas on how to get this working?

Thanks!

**Comment by roemhildtg** [comment]
Did you find that worked for you? I ended up switching themes to the nihilo dojo theme as dbootstrap is no longer maintained.

**Comment by roemhildtg** [comment]
Feel free to reopen if you encounter issues.
