### ISSUE TITLE
AppSettings template not loading

### ISSUE THREAD

**Issue by wrightgd** [roemhildtg/CMV_Widgets#8]
@roemhildtg I am trying to implement your AppSettings widget to allow email links to specific extents within my CMV application.

I have loaded it "off-the-shelf" from your github repo, but I'm getting a strange error when I open my application.  The widget TitlePane is loading on the left of my app, but expanding the TitlePane reveals that it's empty.

Any ideas? Thanks!

Here's what's coming up in the console:

```javascript
Uncaught TypeError: Cannot read property 'ownerDocument' of null
b.place	@	init.js:158
declare._handleShare	@	_shareMixin.js:30
declare._init	@	AppSettings.js:73
declare._loadAppSettings	@	AppSettings.js:142
declare.postCreate	@	AppSettings.js:68
z.create	@	_WidgetBase.js:6
z.postscript	@	_WidgetBase.js:4
(anonymous function)	@	init.js:108
createWidget	@	Controller.js:529
g._hitchArgs	@	init.js:176
ha	@	init.js:32
(anonymous function)	@	init.js:33
ia	@	init.js:33
fa	@	init.js:33
g	@	init.js:35
(anonymous function)	@	init.js:40
```

Here's the relevant excerpt from viewer.js:

```javascript
settings: {
	include: true,
	id: 'settings',
	position: 10,
	type: 'titlePane',
	path: 'gis/dijit/AppSettings',
	title: 'Save/Share Current Map',
	options: {
		//required:
		 map: true,
		 layerControlLayerInfos: true,
		 //optional: 
		 appSettings: {},
		 parametername: 'cmvSettings',
		 mapRightClickMenu: true,
		 address: 'email@email.com',
		 subject: 'Share Map',
		 body: 'Check out this map! <br /> ',
		 emailSettings: ['saveMapExtent', 'savelayerVisibility'],
		 shareNode: ''
		 //shareTemplate: ''
	}
}
```

**Comment by roemhildtg** [comment]
Good catch. It was checking for `shareNode === null` and trying to place the shareNode link at a domNode that didn't exist. Try the latest update, it should be fixed.

**Comment by wrightgd** [comment]
Thanks, will try now and report back momentarily.  Also, please note that in the AppSettings readme, a comma is missing after body: 'Check out this map! <br /> '.  This initially caused errors but was an easy fix on my end.

**Comment by wrightgd** [comment]
This fix worked. Thank you for your help. I will note, however, that HTML such as `<br />` doesn't appear to be supported by the `body` element of a `mailto` url string. The result of this was that `"<br />"` was showing up inline with the body of the email message that got generated.

One potential fix to this is to change `<br />` to `%0D` which is the ASCII encoding for a new line.

Thanks again!
